In [16]:
import pandas as pd
import datetime

InputDir = '../../data/raw'
data = pd.read_csv('%s/date_info.csv' % InputDir, parse_dates=['calendar_date']).rename(columns={'calendar_date': 'visit_date'})

start = datetime.datetime(2016, 12, 25) - datetime.timedelta(days= 7)
end = datetime.datetime(2016, 12, 25)
data['before_christmas'] = data['visit_date'].apply(lambda dt: ((dt <= end) and (dt >= start)))
data['before_christmas'] = data['before_christmas'].astype(int)
start = datetime.datetime(2016, 12, 25)
end = datetime.datetime(2016, 12, 25) + datetime.timedelta(days= 7)
data['after_christmas'] = data['visit_date'].apply(lambda dt: ((dt <= end) and (dt >= start)))
data['after_christmas'] = data['after_christmas'].astype(int)
print(data['before_christmas'].value_counts())

False    509
True       8
Name: before_christmas, dtype: int64

In [4]:
data

    visit_date day_of_week  holiday_flg  before_christmas
0   2016-01-01      Friday            1               1.0
1   2016-01-02    Saturday            1               1.0
2   2016-01-03      Sunday            1               1.0
3   2016-01-04      Monday            0               1.0
4   2016-01-05     Tuesday            0               1.0
5   2016-01-06   Wednesday            0               1.0
6   2016-01-07    Thursday            0               1.0
7   2016-01-08      Friday            0               1.0
8   2016-01-09    Saturday            0               1.0
9   2016-01-10      Sunday            0               1.0
10  2016-01-11      Monday            1               1.0
11  2016-01-12     Tuesday            0               1.0
12  2016-01-13   Wednesday            0               1.0
13  2016-01-14    Thursday            0               1.0
14  2016-01-15      Friday            0               1.0
15  2016-01-16    Saturday            0               1.0
16  2016-01-17      Sunday            0               1.0
17  2016-01-18      Monday            0               1.0
18  2016-01-19     Tuesday            0               1.0
19  2016-01-20   Wednesday            0               1.0
20  2016-01-21    Thursday            0               1.0
21  2016-01-22      Friday            0               1.0
22  2016-01-23    Saturday            0               1.0
23  2016-01-24      Sunday            0               1.0
24  2016-01-25      Monday            0               1.0
25  2016-01-26     Tuesday            0               1.0
26  2016-01-27   Wednesday            0               1.0
27  2016-01-28    Thursday            0               1.0
28  2016-01-29      Friday            0               1.0
29  2016-01-30    Saturday            0               1.0
..         ...         ...          ...               ...
487 2017-05-02     Tuesday            0               NaN
488 2017-05-03   Wednesday            1               NaN
489 2017-05-04    Thursday            1               NaN
490 2017-05-05      Friday            1               NaN
491 2017-05-06    Saturday            0               NaN
492 2017-05-07      Sunday            0               NaN
493 2017-05-08      Monday            0               NaN
494 2017-05-09     Tuesday            0               NaN
495 2017-05-10   Wednesday            0               NaN
496 2017-05-11    Thursday            0               NaN
497 2017-05-12      Friday            0               NaN
498 2017-05-13    Saturday            0               NaN
499 2017-05-14      Sunday            0               NaN
500 2017-05-15      Monday            0               NaN
501 2017-05-16     Tuesday            0               NaN
502 2017-05-17   Wednesday            0               NaN
503 2017-05-18    Thursday            0               NaN
504 2017-05-19      Friday            0               NaN
505 2017-05-20    Saturday            0               NaN
506 2017-05-21      Sunday            0               NaN
507 2017-05-22      Monday            0               NaN
508 2017-05-23     Tuesday            0               NaN
509 2017-05-24   Wednesday            0               NaN
510 2017-05-25    Thursday            0               NaN
511 2017-05-26      Friday            0               NaN
512 2017-05-27    Saturday            0               NaN
513 2017-05-28      Sunday            0               NaN
514 2017-05-29      Monday            0               NaN
515 2017-05-30     Tuesday            0               NaN
516 2017-05-31   Wednesday            0               NaN

[517 rows x 4 columns]